packages:
  - 'apps/*'
  - 'frontend'
  - 'backend'
  - 'packages/**'
allowBuilds:
  '@prisma/client': set this to true or false
overrides:
  typescript-config: link:../packages/config/typescript-config
